# Generated by Django 4.0.3 on 2022-03-19 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnwnedFigurine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('figurine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.figurine')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='RentedFigurine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_date', models.DateField()),
                ('returned_date', models.DateField()),
                ('owned_figurine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.onwnedfigurine')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_id', to='store.user')),
                ('renter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renter_id', to='store.user')),
            ],
        ),
        migrations.CreateModel(
            name='FigurineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('figurine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.figurine')),
            ],
        ),
    ]
