# Generated by Django 4.0.3 on 2022-03-19 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_onwnedfigurine_rentedfigurine_figurineimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
