# Generated by Django 4.0.3 on 2022-03-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurineimage',
            name='image_name',
            field=models.CharField(default='Nameless', max_length=50),
        ),
    ]
