# Generated by Django 4.0.3 on 2022-03-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_figurineimage_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figurineimage',
            old_name='figurine_id',
            new_name='figurine',
        ),
        migrations.RenameField(
            model_name='onwnedfigurine',
            old_name='figurine_id',
            new_name='figurine',
        ),
        migrations.RenameField(
            model_name='onwnedfigurine',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rentedfigurine',
            old_name='owned_figurine_id',
            new_name='owned_figurine',
        ),
        migrations.RenameField(
            model_name='rentedfigurine',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='rentedfigurine',
            old_name='renter_id',
            new_name='renter',
        ),
    ]
