# Generated by Django 4.0.3 on 2022-03-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_figurine_id_figurineimage_figurine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurineimage',
            name='image_name',
            field=models.CharField(max_length=50),
        ),
    ]
